expose:
  type: ingress

  ingress:
    className: nginx
    hosts:
      core: harbor.gcloud.in

  tls:
    enabled: false

externalURL: http://harbor.gcloud.in

harborAdminPassword: Harbor12345

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 20Gi
    database:
      size: 5Gi
    redis:
      size: 2Gi

trivy:
  enabled: true